version = 0.1

[default.deploy.parameters]
stack_name = "game-vibe-plane-pipeline"
resolve_s3 = true
s3_prefix = "game-vibe-plane-pipeline"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GitHubOwner=\"lequockhanh19521680\" GitHubRepo=\"Game-Vibe-Plane\" GitHubBranch=\"main\" CodeStarConnectionArn=\"arn:aws:codeconnections:ap-southeast-1:492098925520:connection/7ae68af2-2294-4762-ae00-74a189937d6a\" DomainName=\"\" CertificateArn=\"\""
image_repositories = []
